In [7]:
import numpy as np
import pandas as pd
import tensorflow as tf
%load_ext autoreload
%autoreload 2


2023-11-16 14:58:51.699329: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0


In [2]:
tf.__version__

'2.5.0'

In [29]:
import lemmyz

ModuleNotFoundError: No module named 'lemmyz'

In [ ]:
import re
word_list = ["et", "en", "den", "denne", "fået", "bilen", "etikette", "anden", "pennen", "kanin"]


# pattern = r'(\b(et|en|den|dens|denne)\b)'
pattern = r'^(?:et|en|den|dens|denne)\b'
filtered_words = [word for word in word_list if not re.search(pattern, word, re.IGNORECASE)]

filtered_words


In [ ]:
import re
word_list = ["maj", "åmaj"]


# pattern = r'(\b(et|en|den|dens|denne)\b)'
pattern = r'(?<=[\s]|^)mandag(?:s|en|e?)?(?=[\s]|$)'
filtered_words = [word for word in word_list if not re.search(pattern, word, re.IGNORECASE)]

filtered_words

In [ ]:
s = "Oscar Fisker Mølgaard og Kristers Steinbergs er blandt de udvalgte til VM-testkampene mod Sverige i næste uge."
sentence_trimmed = s.rstrip(".")

sentence_trimmed

In [ ]:
from create_vocab import split_sentences, strip_sentences
a = ["foo", "bar", "foo "]

import collections
print([item for item, count in collections.Counter(strip_sentences(a)).items() if count > 1])

## [1, 2, 5]

[]


In [ ]:
# def strip_strings(strs):
#     stripped = []
#     for s in strs:
#         stripped.append(s.rstrip(". ").strip()) # removes trailing newline and full stop and space
#     return stripped

# strs = ["Eksperter er yderst imponeret over Wozniackis indsats. ", "fsdfsdff"]

# strip_strings(strs)


['Eksperter er yderst imponeret over Wozniackis indsats', 'fsdfsdff']

In [ ]:

from csv_data import get_all_articles


# {'3', '\r', '5', 'Á', '6', 'U', 'ø', 'X', ' ', 'E', 'J', 'ï', 'Æ', 'f', 'Ö', '4', '«', 'G', 'W', 'I', 'B', 'ñ', '8', 's', '\n', 'Í', 'î', 'A', '»', 'R', '!', '\x85', 'K', 'r', 'g', 'z', 'æ', 'H', '#', 'á', '/', '7', 'Ø', 'ã', '2', 'v', ':', 'ö', '?', 'j', ',', 'Z', 'D', 'd', 'n', 'ó', 'Å', 'F', 'ü', 'q', "'", 'ä', 'o', 'e', 'u', 'c', 'Y', 'N', 'V', 'b', 'è', 'k', 'é', 'P', '+', '9', '\xa0', 'C', 'L', 'h', '"', 'y', 't', 'ú', 'T', '.', 'ç', 'M', 'S', 'x', 'O', '&', '´', 'i', 'ë', '-', '0', 'w', 'í', 'Q', 'É', '1', '(', 'a', 'p', ')', 'l', 'å', 'm'}

def replace_spaces(text):
    pattern = r'[\s\xa0]'
    return re.sub(pattern, ' ', text)

def extract_data(df):
    train_text = df.iloc[:, [0,1,2]].apply(' . '.join, axis=1).to_numpy()
    # train_text = [replace_spaces(text) for text in train_text]
    train_text = strip_strings(train_text)

    labels = df['isResult'].to_numpy().astype(int)

    return train_text, labels

d = get_all_articles()

train_text, labels = extract_data(get_all_articles())


lst = []
 
for sentence in train_text:
    letters = [x for x in sentence]


    lst.extend(letters) 

s = set(lst)

print(len(s))
print(s)


109
{'3', '\r', '5', 'Á', '6', 'U', 'ø', 'X', ' ', 'E', 'J', 'ï', 'Æ', 'f', 'Ö', '4', '«', 'G', 'W', 'I', 'B', 'ñ', '8', 's', '\n', 'Í', 'î', 'A', '»', 'R', '!', '\x85', 'K', 'r', 'g', 'z', 'æ', 'H', '#', 'á', '/', '7', 'Ø', 'ã', '2', 'v', ':', 'ö', '?', 'j', ',', 'Z', 'D', 'd', 'n', 'ó', 'Å', 'F', 'ü', 'q', "'", 'ä', 'o', 'u', 'e', 'c', 'Y', 'N', 'V', 'b', 'è', 'k', 'é', 'P', '9', '+', '\xa0', 'C', 'L', 'h', '"', 'y', 't', 'ú', 'T', '.', 'ç', 'M', 'S', 'x', 'O', '&', '´', 'i', 'ë', '-', '0', 'w', 'í', 'Q', 'É', '1', '(', 'a', 'p', ')', 'l', 'å', 'm'}


In [ ]:
train_text

In [ ]:
from utils import to_lower_case

w = text_formatter("fsdfds")
w


'fsdfds'

In [ ]:
df_ddo_vocab = pd.read_table('resources/ddo_fullforms_2020-08-26.csv', header=None)

df_vocab_select_columns = df_ddo_vocab.iloc[:, [0,1]]
vocab_all_values = df_vocab_select_columns.values.ravel()
from collections import OrderedDict

print(len(s))

d = vocab_2_dict(s)


l1 = ["dsfds", "vdgdfdg"]
l2 = ["jjhgj", "nmbvnvf"]


ll = np.concatenate([l1, l2]) 
s = set(ll)
OrderedDict.fromkeys(s)


4


OrderedDict([('nmbvnvf', None),
             ('dsfds', None),
             ('jjhgj', None),
             ('vdgdfdg', None)])

In [ ]:
import time
isin_dict = False
def test_lookup_performance():
    word_to_check = "Dansk"
    start_time = time.time()

    for x in range(10000000):
        isin_dict = word_to_check in d

    end_time = time.time()  
    assert(end_time - start_time < 1)
    print(isin_dict)

test_lookup_performance()

False


In [ ]:
def remove_danske_navne(words, danske_navne):
    words_minus_danske_navne = []
    for w in words:
        result = any(w.startswith(item) for item in danske_navne)
        if result == False:
            words_minus_danske_navne.append(w)
    
    return list(set(words_minus_danske_navne))


remove_danske_navne(["foo"], ["bar"])

['foo']

In [ ]:
sentences_total, labels_total = get_all_articles(shuffle=False)

allowed_characters = ['3', '\r', '5', 'Á', '6', 'U', 'ø', 'X', ' ', 'E', 'J', 'ï', 'Æ', 'f', 'Ö', '4', '«', 'G', 'W', 'I', 'B', 'ñ', '8', 's', '\n', 'Í', 'î', 'A', '»', 'R', '!', '\x85', 'K', 'r', 'g', 'z', 'æ', 'H', '#', 'á', '/', '7', 'Ø', 'ã', '2', 'v', ':', 'ö', '?', 'j', ',', 'Z', 'D', 'd', 'n', 'ó', 'Å', 'F', 'ü', 'q', "'", 'ä', 'o', 'e', 'u', 'c', 'Y', 'N', 'V', 'b', 'è', 'k', 'é', 'P', '+', '9', '\xa0', 'C', 'L', 'h', '"', 'y', 't', 'ú', 'T', '.', 'ç', 'M', 'S', 'x', 'O', '&', '´', 'i', 'ë', '-', '0', 'w', 'í', 'Q', 'É', '1', '(', 'a', 'p', ')', 'l', 'å', 'm']


total_chars = []
for sentence in sentences_total:
    chars = [x for x in sentence]

total_chars_set = set(total_chars)

print(total_chars_set)

type(labels_total[0])

assert (isinstance(labels_total[0], np.int64) == True)

{'d', 't', 'ú', '3', 'î', '5', '.', 'n', '»', 'ç', '!', 'ó', '6', 'ü', 'x', '&', 'ø', '´', 'q', "'", 'ä', 'o', 'e', 'u', 'i', 'r', 'ë', ' ', 'c', '-', '0', 'g', 'w', 'z', 'í', 'æ', 'b', '#', 'è', '1', '(', 'ï', 'a', 'k', 'é', 'f', 'á', '4', 'p', '9', '/', ')', '+', '«', '7', 'ã', 'h', '"', 'l', 'å', 'v', ':', 'm', 'y', '2', 'ö', '?', 'ñ', 'j', ',', '8', 's'}


In [87]:



new_str = tf.strings.regex_replace(word, pattern=r'([^a-zæøåA-ZÆØÅ\d\sñé])', rewrite=r' \1 ', replace_global=True)

c = [' ', 'ñ', 'z', 'ä', 'n', '?', '#', '"', 'g', '»', '7', 'm', 's', 'e', '8', '5', '&', '9', 'f', 'æ', 'ö', 'î', '1', '´', 'ç', 'í', 'ã', 'w', 'y', '-', 'b', 'ú', 'c', '4', '2', 't', 'é', '/', 'o', ',', '6', "'", '.', 'ï', 'x', 'ø', 'k', '(', 'è', 'j', '«', '0', 'q', 'å', 'h', 'v', 'r', 'd', 'l', ':', 'ü', 'á', '+', 'ë', '3', ')', 'ó', 'p', 'a', 'i', '!', 'u']



new_str.numpy().decode("UTF-8")

'foo - bar'

In [203]:
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization
from vectorization import standardize
from vectorization import vectorize_layer
from vectorization import vect_layer_2_text

s = "a-zæøåñäöîçíãúéïèüáëó0-9"

pattern = rf"([{s}]+|\S)"

def split_specials(word):
    return re.findall(pattern, word)

    # ñäöîçíãúéïèüáëó

def split_included_specials(word):
    print(word)
    new_str = tf.strings.regex_replace(word, pattern=pattern, rewrite=r' \1 ', replace_global=True)
    return new_str

new_str = tf.strings.regex_replace("fodbold tour øland france poka:len", pattern=rf'([^{s}\s])', rewrite=r' \1 ', replace_global=True)

print(new_str.numpy().decode())

def split_sentences(sentences):
    words_arr = []
    for sentence in sentences:
        words = split_specials(sentence)
        words_arr.extend(words)
    return words_arr

print(split_sentences(["fodbold tour øland france poka:len"]))



fodbold tour øland france poka : len
['fodbold', 'tour', 'øland', 'france', 'poka', ':', 'len']


In [234]:
from vectorization import replace_nationality

from vectorization import replace_finals
from vectorization import replace_nationality
from vectorization import to_lower
from vectorization import remove_dash
from vectorization import split_included_specials
from vectorization import replace_tournament
from vectorization import replace_countries
from vectorization import replace_weekday
from vectorization import replace_digits
from vectorization import vect_layer_2_text
from vectorization import vectorize_layer
from vectorization import standardize
from static_data import tournaments
from static_data import weekdays
from static_data import non_alpha
from static_data import word_generalization

nationalities = csv_list_to_list('resources/nat2.csv')
danske_navne = csv_list_to_list('resources/danmark_navne.csv')
andre_navne = csv_list_to_list('resources/andre_navne.csv')
countries = csv_list_to_list('resources/countries.csv')
navne = csv_list_to_list('resources/navne.csv')

r = replace_nationality(nationalities)

r("sydtyskere")

arrs = [
    to_lower, 
    remove_dash, 
    split_included_specials, 
    replace_tournament(tournaments),
    replace_countries(countries), 
    replace_weekday(weekdays), 
    replace_finals,
    replace_nationality(nationalities),
    replace_digits
]

s = standardize(arrs)

s("danske bøller er foo-bar").numpy().decode().split()




['xnationality', 'bøller', 'er', 'foo', 'bar']

In [250]:

new_str = "dansker"
nationalities = csv_list_to_list('resources/nat2.csv')
def replace_nationality(word):
    new_str = word
    for sign in nationalities:
        r = "\\b(?:nord|syd|øst|vest)?" + sign + "(?:eren|erne|ere|ne|en|er|r|e|isk)?" + "(\w*)\\b"
        new_str = tf.strings.regex_replace(new_str, pattern=r,  rewrite=r'xnationality \1')

    return new_str

replace_nationality("makedonsk")

<tf.Tensor: shape=(), dtype=string, numpy=b'xnationality '>

In [1]:
import tensorflowjs as tfjs

tfjs.converters.convert

2023-11-15 14:14:31.341224: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-15 14:14:31.858209: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [11]:
from csv_data import get_vocab_dict
from csv_data import get_all_articles
from csv_data import csv_list_to_list
from csv_data import split_data
from csv_data import check_duplicates


nationalities = csv_list_to_list('resources/nationalities.csv')
countries = csv_list_to_list('resources/countries.csv')


c = ("(" + "|".join(countries) + ")")

s = "\\b(?:nord|syd|øst|vest)?" + c + "s?\\b"

j = {"countries" : s}

import json

with open('regexes.json', 'w',  encoding='utf8') as file:
    json.dump(j, file, ensure_ascii=False)




def replace_countries(word):

    new_str = word
    # for sign in countries:
    r = "\\b(?:nord|syd|øst|vest)?" + c + "s?\\b"
    new_str = tf.strings.regex_replace(new_str, pattern=r, rewrite="xland")

    return new_str


replace_countries("albanien danmark")

<tf.Tensor: shape=(), dtype=string, numpy=b'xland xland'>

In [21]:
nationalities = csv_list_to_list('resources/nationalities.csv')
def nationalities_regex():
    nationalities_joined = ("(?:" + "|".join(nationalities) + ")")
    return "\\b(?:nord|syd|øst|vest)?" + nationalities_joined + "(?:eren|erne|ere|ne|en|er|r|e|isk)?" + "(\w*)\\b"

n = nationalities_regex()

s = tf.strings.regex_replace("englænder", pattern=n, rewrite=r'xnationality \1')

print(s)


tf.Tensor(b'xnationality ', shape=(), dtype=string)


In [32]:

new_str = tf.strings.regex_replace("fsdfs", pattern=r'([^a-zæøåñäöîçíãúéïèüáëó0-9\s])', rewrite=r' \1 ', replace_global=True)

new_str

<tf.Tensor: shape=(), dtype=string, numpy=b'fsd fs'>